/**
 * Pins the Cmd+K command palette contract.
 *
 * A keyboard-driven launcher for navigation, settings,
 * theme + font size, help articles, and quick actions.
 *
 * Wires up Primer's design tokens. Cross-component triggers
 * (open Settings, open Chat, open Focus editor, open Shortcuts)
 * dispatch CustomEvents on `window` rather than threading
 * callbacks through props — same pattern Primer already uses for
 * `primer:tts-voice-changed` and the per-block code-theme switcher.
 */

import { describe, expect, it } from "vitest";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";

const REPO_ROOT = resolve(__dirname, "..", "..");
const read = (p: string) => readFile(resolve(REPO_ROOT, p), "utf-8");

describe("CommandPalette: open / close behavior", () => {
  it("opens on Cmd+K and Ctrl+K, prevents default early", async () => {
    const src = await read("src/frontend/components/CommandPalette.tsx");
    expect(src).toMatch(
      /\(event\.metaKey \|\| event\.ctrlKey\) && event\.key\.toLowerCase\(\) === "k"/,
    );
    expect(src).toMatch(/event\.preventDefault\(\)/);
  });

  it("toggles open state — pressing Cmd+K again from inside the palette closes it", async () => {
    const src = await read("src/frontend/components/CommandPalette.tsx");
    expect(src).toMatch(/setOpen\(\(prev\) => !prev\)/);
  });

  it("supports an opt-out (`data-allow-cmdk='false'`) for inputs with their own Cmd+K binding", async () => {
    const src = await read("src/frontend/components/CommandPalette.tsx");
    expect(src).toMatch(/dataset\.allowCmdk === "false"/);
  });

  it("can be opened programmatically via the `primer:open-command-palette` event", async () => {
    const src = await read("src/frontend/components/CommandPalette.tsx");
    // The exported wire-format string is now generated by
    // `primerEventName("open-command-palette")` (typed bus), but
    // the alias name + the typed-bus subscription are both still
    // pinned. New callers should use the bus directly; legacy
    // raw-`addEventListener` consumers still work because the
    // wire-format string is unchanged.
    expect(src).toMatch(
      /export const COMMAND_PALETTE_OPEN_EVENT = primerEventName\("open-command-palette"\)/,
    );
    expect(src).toMatch(/onPrimerEvent\("open-command-palette"/);
  });

  it("closes on Escape and resets query + selection", async () => {
    const src = await read("src/frontend/components/CommandPalette.tsx");
    expect(src).toMatch(
      /event\.key === "Escape"[\s\S]{0,200}close\(\)/,
    );
    expect(src).toMatch(
      /const close = useCallback[\s\S]{0,200}setOpen\(false\)[\s\S]{0,200}setQuery\(""\)[\s\S]{0,200}setSelectedIndex\(0\)/,
    );
  });
});

describe("CommandPalette: keyboard navigation", () => {
  it("Arrow Up / Arrow Down move the selected index, clamped to bounds", async () => {
    const src = await read("src/frontend/components/CommandPalette.tsx");
    expect(src).toMatch(
      /event\.key === "ArrowDown"[\s\S]{0,200}Math\.min\(prev \+ 1, filtered\.length - 1\)/,
    );
    expect(src).toMatch(
      /event\.key === "ArrowUp"[\s\S]{0,200}Math\.max\(prev - 1, 0\)/,
    );
  });

  it("Enter runs the highlighted item's action", async () => {
    const src = await read("src/frontend/components/CommandPalette.tsx");
    expect(src).toMatch(/event\.key === "Enter"[\s\S]{0,200}filtered\[selectedIndex\]\.action\(\)/);
  });

  it("scrolls the highlighted row into view as the user navigates", async () => {
    const src = await read("src/frontend/components/CommandPalette.tsx");
    expect(src).toMatch(/scrollIntoView\(\{ block: "nearest" \}\)/);
  });

  it("resets selection to 0 whenever the query changes", async () => {
    const src = await read("src/frontend/components/CommandPalette.tsx");
    expect(src).toMatch(
      /useEffect\(\(\) => \{[\s\S]{0,80}setSelectedIndex\(0\);[\s\S]{0,80}\}, \[query\]\)/,
    );
  });
});

describe("CommandPalette: items + categories", () => {
  it("includes every top-level NAV page", async () => {
    const src = await read("src/frontend/components/CommandPalette.tsx");
    // Each must appear as an entry in NAV_PAGES so the palette is
    // a complete launcher.
    expect(src).toMatch(/path: "\/", label: "Briefing"/);
    expect(src).toMatch(/path: "\/concepts", label: "Concepts"/);
    expect(src).toMatch(/path: "\/archive", label: "Archive"/);
    expect(src).toMatch(/path: "\/analytics", label: "Analytics"/);
    expect(src).toMatch(/path: "\/bookmarks", label: "Bookmarks"/);
    expect(src).toMatch(/path: "\/help", label: "Help"/);
  });

  it("exposes the four quick actions: Settings, Focus editor, Chat, Shortcuts", async () => {
    const src = await read("src/frontend/components/CommandPalette.tsx");
    expect(src).toMatch(/id: "action-open-settings"/);
    expect(src).toMatch(/id: "action-open-focus"/);
    expect(src).toMatch(/id: "action-open-chat"/);
    expect(src).toMatch(/id: "action-open-shortcuts"/);
  });

  it("each action dispatches the right typed bus event", async () => {
    const src = await read("src/frontend/components/CommandPalette.tsx");
    // Migrated from raw `window.dispatchEvent(new CustomEvent(...))`
    // to the typed `dispatchPrimerEvent` from lib/events.ts. The
    // wire-format strings are unchanged (`primer:open-settings` /
    // `primer:open-chat` / etc.) so legacy raw-listener consumers
    // still fire — only the dispatch path is now type-checked.
    expect(src).toMatch(/dispatchPrimerEvent\("open-settings"\)/);
    expect(src).toMatch(/dispatchPrimerEvent\("open-focus-editor"\)/);
    expect(src).toMatch(/dispatchPrimerEvent\("open-chat"\)/);
    expect(src).toMatch(/dispatchPrimerEvent\("open-shortcuts"\)/);
  });

  it("includes theme + font-size pickers with a 'current' annotation", async () => {
    const src = await read("src/frontend/components/CommandPalette.tsx");
    // Theme + font-size loops emit one item per option, each tagged
    // with `hint: theme === opt.value ? "current" : undefined`.
    expect(src).toMatch(/hint: theme === opt\.value \? "current" : undefined/);
    expect(src).toMatch(/hint: fontSize === opt\.value \? "current" : undefined/);
  });

  it("includes every help article so the palette doubles as docs search", async () => {
    const src = await read("src/frontend/components/CommandPalette.tsx");
    expect(src).toMatch(/getAllHelpPages\(\)/);
    expect(src).toMatch(/category: "Help"/);
    expect(src).toMatch(/navigate\(`\/help\/\$\{page\.id\}`\)/);
  });

  it("matches the user's query against label, category, hint, AND keywords", async () => {
    const src = await read("src/frontend/components/CommandPalette.tsx");
    // Keywords let "preferences" find Settings and "saved" find
    // Bookmarks even when those words don't appear in the label.
    expect(src).toMatch(/item\.label\.toLowerCase\(\)\.includes\(q\)/);
    expect(src).toMatch(/item\.category\.toLowerCase\(\)\.includes\(q\)/);
    expect(src).toMatch(/item\.hint\?\.toLowerCase\(\)\.includes\(q\)/);
    expect(src).toMatch(/item\.keywords\?\.some\(\(k\) => k\.toLowerCase\(\)\.includes\(q\)\)/);
  });
});

describe("CommandPalette: cross-component event listeners", () => {
  it("Header listens for open-settings + open-focus-editor via typed bus", async () => {
    const src = await read("src/frontend/components/Header.tsx");
    expect(src).toMatch(/import \{ onPrimerEvent \} from "\.\.\/lib\/events"/);
    expect(src).toMatch(/onPrimerEvent\("open-settings",/);
    expect(src).toMatch(/onPrimerEvent\("open-focus-editor",/);
  });

  it("App listens for open-chat via typed bus", async () => {
    const src = await read("src/frontend/App.tsx");
    expect(src).toMatch(/import \{ onPrimerEvent \} from "\.\/lib\/events"/);
    expect(src).toMatch(/onPrimerEvent\("open-chat",/);
  });

  it("App mounts <CommandPalette /> exactly once at the app shell", async () => {
    const src = await read("src/frontend/App.tsx");
    const matches = src.match(/<CommandPalette \/>/g) ?? [];
    expect(matches.length).toBe(1);
  });

  it("ShortcutsDialog listens for open-shortcuts via typed bus", async () => {
    const src = await read("src/frontend/components/ShortcutsDialog.tsx");
    expect(src).toMatch(/import \{ onPrimerEvent \} from "\.\.\/lib\/events"/);
    expect(src).toMatch(/onPrimerEvent\("open-shortcuts",/);
  });

  it("ShortcutsDialog lists Cmd+K as the first row in its shortcut groups", async () => {
    const src = await read("src/frontend/components/ShortcutsDialog.tsx");
    // Pin both that the group exists and that Cmd+K shows up.
    expect(src).toMatch(/title: "Command Palette"/);
    expect(src).toMatch(
      /title: "Command Palette"[\s\S]{0,300}keys: \["Cmd", "K"\]/,
    );
  });
});

describe("CommandPalette: accessibility", () => {
  it("renders a role='dialog' overlay with aria-modal and a label", async () => {
    const src = await read("src/frontend/components/CommandPalette.tsx");
    expect(src).toMatch(/role="dialog"/);
    expect(src).toMatch(/aria-modal="true"/);
    expect(src).toMatch(/aria-label="Command palette"/);
  });

  it("focuses the search input when opened", async () => {
    const src = await read("src/frontend/components/CommandPalette.tsx");
    expect(src).toMatch(
      /useEffect\(\(\) => \{[\s\S]{0,150}if \(open\) inputRef\.current\?\.focus\(\)/,
    );
  });
});

describe("Keyboard-shortcuts help doc covers the new Cmd+K binding", () => {
  it("includes a Command Palette section", async () => {
    const src = await read("src/frontend/help/reference/keyboard-shortcuts.md");
    expect(src).toMatch(/## Command Palette/);
    expect(src).toMatch(/Cmd \+ K/);
    expect(src).toMatch(/Ctrl \+ K/);
  });

  it("documents the data-allow-cmdk opt-out", async () => {
    const src = await read("src/frontend/help/reference/keyboard-shortcuts.md");
    expect(src).toMatch(/data-allow-cmdk="false"/);
  });
});
